{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.12.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.23"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.5.jar",
          "url": "spring-boot-starter-data-jpa-2.7.5.jar",
          "size": 4758,
          "sha512": "a01fb4914d0a018016a542933ee28edb4782a2687bc0ad2d5269bfc3dc624c9bd7f44da7c9aaae61b68fa0220b188e226a13a352e9ca2242afca06ea5309a2ef",
          "sha256": "6a3b6db4cebdd32db94497975f0ed6b84a336e62aa4ba5ca0e56eb80ccf3547c",
          "sha1": "b83184467079d5b808fb2f9fbc858b1804975808",
          "md5": "fb1647e45cd440d75d006cd98e3837a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.12.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.23"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.5.jar",
          "url": "spring-boot-starter-data-jpa-2.7.5.jar",
          "size": 4758,
          "sha512": "a01fb4914d0a018016a542933ee28edb4782a2687bc0ad2d5269bfc3dc624c9bd7f44da7c9aaae61b68fa0220b188e226a13a352e9ca2242afca06ea5309a2ef",
          "sha256": "6a3b6db4cebdd32db94497975f0ed6b84a336e62aa4ba5ca0e56eb80ccf3547c",
          "sha1": "b83184467079d5b808fb2f9fbc858b1804975808",
          "md5": "fb1647e45cd440d75d006cd98e3837a5"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.5.jar",
          "url": "spring-boot-starter-data-jpa-2.7.5.jar",
          "size": 4758,
          "sha512": "a01fb4914d0a018016a542933ee28edb4782a2687bc0ad2d5269bfc3dc624c9bd7f44da7c9aaae61b68fa0220b188e226a13a352e9ca2242afca06ea5309a2ef",
          "sha256": "6a3b6db4cebdd32db94497975f0ed6b84a336e62aa4ba5ca0e56eb80ccf3547c",
          "sha1": "b83184467079d5b808fb2f9fbc858b1804975808",
          "md5": "fb1647e45cd440d75d006cd98e3837a5"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.5.jar",
          "url": "spring-boot-starter-data-jpa-2.7.5.jar",
          "size": 4758,
          "sha512": "a01fb4914d0a018016a542933ee28edb4782a2687bc0ad2d5269bfc3dc624c9bd7f44da7c9aaae61b68fa0220b188e226a13a352e9ca2242afca06ea5309a2ef",
          "sha256": "6a3b6db4cebdd32db94497975f0ed6b84a336e62aa4ba5ca0e56eb80ccf3547c",
          "sha1": "b83184467079d5b808fb2f9fbc858b1804975808",
          "md5": "fb1647e45cd440d75d006cd98e3837a5"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.5-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.7.5-javadoc.jar",
          "size": 4749,
          "sha512": "e3323847f3c8d3e8e508171112116b9f41e784a803283d969241a226fc258a6035c751e86afa74c726c469cd5ec2a84c9dd2c1a083aa8a2422b13bedd50499c1",
          "sha256": "752844aa832f2ad5c42602dacdf3cb94a3fb0ff7fa88558e2510a2936f5b1a4e",
          "sha1": "89e329ff1baaf0f42699b6c402eccf957b300535",
          "md5": "c876775a0f64daef6cdc0f2ea8ab1e01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.5-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.7.5-sources.jar",
          "size": 4747,
          "sha512": "544dc23565cd9cc09acd26316279012d1dcc9b55388afd05338bb9d6ecac87e4c9bf7942563b73095a485675d752e1667e10d3f13e6ba6b8cb2a5854e0f28cb8",
          "sha256": "fd1fd2f603bfc2dd3a3d68199dbbeded73b10fbd5aeb526f80af69e6dfd85003",
          "sha1": "b7b26640f14c91c49294df8f8786f420dc72bf21",
          "md5": "1dfeda6d21ce773c8f94be4b7014d102"
        }
      ]
    }
  ]
}
